export * from "./home";
export * from "./login";
export * from "./register";
export * from "./assignmentList";
export * from "./result";
export * from "./assignmentDetail";
export * from "./studentResultDetailPage";
export * from "./teacherResultDetailPage";
export * from "./teacherSubjectPage";